//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnosBus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class bus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bus()
        {
            this.frequencies = new HashSet<frequency>();
            this.turns = new HashSet<turn>();
        }
    
        public int id { get; set; }
        [Required]
        [RegularExpression(@"^([A-Z]{3})[-]([0-9]{4})$", ErrorMessage = "La placa debe tener 3 letras mayusculas y 4 digitos. Ejem:XBX-0458 ")]
        public string plate { get; set; }
        [Required]
        [RegularExpression("^\\d+$", ErrorMessage = "El capacidad debe contener sólo números.")]
        public Nullable<int> capacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<frequency> frequencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<turn> turns { get; set; }
    }
}
