//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnosBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class code
    {
        public int id { get; set; }
        public Nullable<int> id_turn { get; set; }
        public string turncode { get; set; }
    
        public virtual turn turn { get; set; }
    }
}
