//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnosBus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TurnosBusEntities : DbContext
    {
        public TurnosBusEntities()
            : base("name=TurnosBusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bus> buses { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<code> codes { get; set; }
        public virtual DbSet<frequency> frequencies { get; set; }
        public virtual DbSet<place> places { get; set; }
        public virtual DbSet<turn> turns { get; set; }
    }
}
